
Grammar Ledger
LedgerCall <- "Ledger" Sep Options / "Ledger" EOS #Command? Arguments? 
Options <-  (FileOpt / SortOpt / PriceOpt)+ 
FileOpt <- File (Sep / EOS)
SortOpt <- Sort (Sep / EOS) 
PriceOpt <- PriceDb (Sep / EOS )
File <- FileFlag Sep FilePath
FileFlag <- "--file" / "-f"
Sort <- SortFlag Sep SortCriteria
SortFlag <- "--sort" / "-S"
SortCriteria <- "d" / "a"
PriceDb <- PriceDbFlag Sep FilePath
PriceDbFlag <- "--price-db"
FilePath <- .* 
Sep <- " "+ 
EOS <- !.
